### ISSUE TITLE
Event Queue Full

### ISSUE THREAD

**Issue by GiulioDallaVecchia** [STMicroelectronics/stm32-mw-usb-host#1] opened 2021-04-13 07:00 UTC
**Describe the set-up**
 * STM32H735G-DK
 * STM32CubeIDE

**Describe the bug**
I'm using the USB Host library with FreeRTOS implementation with CMSIS OS2. Each time I've tried to insert anUSB Stick, the USB Core message queue reach the errQueue_FULL error. 

**How To Reproduce**
1. Create a project with FreeRTOS

2. Added USB Host Library last version (v3.3.5)

3. Insert a USB stick and keep under monitoring the osMessageQueuePut function call

**Screenshots**
![debug](https://user-images.githubusercontent.com/44542412/114510149-9b251d80-9c36-11eb-9222-7f2bb27e26a5.png)

**Comment by ALABSTM** [comment] 2021-04-21 12:28
Hi @GiulioDallaVecchia,

We will try to analyze your report as soon as possible and get back to you as soon as we have an answer. Thank you for your patience.

With regards,

**Comment by RKOUSTM** [comment] 2021-07-06 09:21
Hi @GiulioDallaVecchia,

Thank you for this report. 

If the issue is systematically reproducible on your side, could you please share the whole project so that we can reproduce the same behavior and give you an answer.

With regards,

**Comment by ALABSTM** [comment] 2021-08-02 11:00
Hi @GiulioDallaVecchia,

We hope you are fine. Any project to share or at least an IOC file? Thank you.

With regards,

**Comment by RKOUSTM** [comment] 2021-08-13 18:03
Hi @GiulioDallaVecchia,

Any new comments to move this discussion forward? 

With regards,

**Comment by RKOUSTM** [comment] 2021-08-16 14:32
Hi @GiulioDallaVecchia,

Please allow me to close this thread as no feedback has been received. You can reopen it if you have anything else relevant to add regarding this topic. 

With regards,

**Comment by GiulioDallaVecchia** [comment] 2021-09-01 11:29
Hi @RKOUSTM,

I think it is something similar to https://github.com/STMicroelectronics/STM32CubeF4/issues/34.

If you want I have a ready project. What is the best solution (or platform) for you in order to share the project?

**Comment by ALABSTM** [comment] 2021-10-21 16:25
Hi @GiulioDallaVecchia,

I hope you are fine. Would you mind share the *ready project* you mentioned in your last comment? Basically, the **IOC** file, ideally the whole project in case you brought particular modifications after the generation.

This issue is reopened as new activity has been registered. Looking forward to receiving your files.

With regards,

**Comment by GiulioDallaVecchia** [comment] 2021-10-22 09:43
Hi @ALABSTM,

I'm fine, thanks! I have generated the project from CubeMX, but after I modified the USB_conf.c layer for using _FULL SPEED_ configuration.

I have .zip file that I can share with you. Do you have a private platform or can I use a public service like "_wetransfer_"?

Best regard,

**Comment by ALABSTM** [comment] 2021-10-27 15:47
Hi @GiulioDallaVecchia,

Please excuse my delayed reply. It is fine to share a zipped project. You can simply attach it to your next message as GitHub supports sharing such attachments. To optimize the zipped file's size, it may be interesting to remove all generated files (**e.g.**, *.o, *.out).

I hope this solution is also fine for you.

With regards,

**Comment by GiulioDallaVecchia** [comment] 2021-10-28 06:09
Hi @ALABSTM,

the requested project is here:

[STM32H735DK_USB_TEST.zip](https://github.com/STMicroelectronics/stm32_mw_usb_host/files/7431556/STM32H735DK_USB_TEST.zip)

Best regards,

**Comment by ALABSTM** [comment] 2021-12-22 12:26
Hi @GiulioDallaVecchia,

I hope you are doing well. I want to inform you that I ran the project you sent but could not yet reproduce the issue. I will keep you informed.

With regards,

**Comment by GiulioDallaVecchia** [comment] 2021-12-22 12:49
Hi @ALABSTM,

try to add a variable `num_event` inside USBH_LL_NotifyURBChange in file "usbh_core.c". After that, try to insert a USB stick and look what value achieve `num_event`.

```
static uint32_t num_event;
USBH_StatusTypeDef  USBH_LL_NotifyURBChange(USBH_HandleTypeDef *phost)
{
  phost->os_msg = (uint32_t)USBH_PORT_EVENT;

#if (osCMSIS < 0x20000U)
  (void)osMessagePut(phost->os_event, phost->os_msg, 0U);
#else
  (void)osMessageQueuePut(phost->os_event, &phost->os_msg, 0U, 0U);
  ++num_event;
#endif

  return USBH_OK;
}
```

With regards,

**Comment by ALABSTM** [comment] 2022-04-25 10:37
Hi @GiulioDallaVecchia,

The issue you described has been logged internally and escalated to our USB team. We will get back to you once we have a feedback.

With regards,

**Comment by ALABSTM** [comment] 2022-04-25 10:38
ST Internal Reference: 126912

**Comment by ALABSTM** [comment] 2023-11-22 13:22
Hi @GiulioDallaVecchia,

I hope you are fine. Back to you about this point you submitted a time ago.

Our development teams could reproduce the behavior you described. However, according to them, the queue size is rather a **design choice**, than a limitation. They suggest that the default size of the queue could be **overridden at user's application level**.

Please allow me to close this point in this case. Thank you for your comprehension and for your patience.

Below some feedback from the development teams' observations:
* The queue is used to block/unblock the `USBH_Process_OS()` thread.
* Several functions executing within the context of the USB ISR put events on the queue.
* The `USBH_Process_OS()` thread itself puts events on the queue to keep itself running and process state transitions.
* The events are not used in anyway and seem to serve no other purpose than unblocking `USBH_Process_OS()`.
* The brute force approach of increasing the queue size to a large value eliminates the `errQueue_FULL` issue yet the app behavior is the same. The device is successfully enumerated in both cases.

With regards,

**Closed as not planned by ALABSTM** 2023-11-22 13:22 UTC
Labels: bug, invalid, mw, usb, rtos, internal bug tracker
